"""Skill data model for the progressive disclosure system."""

from datetime import datetime
from typing import (
    List,
    Optional,
)

from pydantic import (
    BaseModel,
    Field,
)


class Skill(BaseModel):
    """A skill that can be progressively disclosed to the agent.

    Skills are lightweight descriptions shown to the agent upfront,
    with full content loaded on-demand via tool calls.

    Attributes:
        name: Unique identifier for the skill.
        description: Brief 1-2 sentence description shown in system prompt.
        content: Full skill content with detailed instructions, loaded on-demand.
        tags: Optional tags for categorization and discovery.
        version: Skill version number, incremented on each update.
        source: Origin of the skill (manual, conversation, agent).
        auto_generated: Whether this skill was auto-generated by SkillCreator.
        created_at: Timestamp when the skill was first created.
        updated_at: Timestamp when the skill was last updated.
    """

    name: str = Field(..., description="Unique identifier for the skill")
    description: str = Field(..., description="Brief description shown in system prompt")
    content: str = Field(..., description="Full skill content loaded on-demand")
    tags: List[str] = Field(default_factory=list, description="Tags for categorization")
    version: int = Field(default=1, description="Skill version, incremented on update")
    source: str = Field(default="manual", description="Origin: manual, conversation, agent")
    auto_generated: bool = Field(default=False, description="Whether auto-generated by SkillCreator")
    created_at: Optional[datetime] = Field(default=None, description="Creation timestamp")
    updated_at: Optional[datetime] = Field(default=None, description="Last update timestamp")
