"""Data models for the Workflow orchestration engine.

Defines the state schemas used by the WorkflowGraph, including
WorkflowStep (individual task), WorkflowPlan (multi-step plan),
WorkflowState (main graph state), and WorkerTaskState (per-worker state for Send).
"""

import operator
from typing import (
    Annotated,
    Optional,
)

from langgraph.graph.message import add_messages
from pydantic import (
    BaseModel,
    Field,
)


class WorkflowStep(BaseModel):
    """A single step in a workflow execution plan.

    Attributes:
        id: Unique identifier for this step (e.g., "step_1").
        worker: Worker name from WORKER_REGISTRY (e.g., "coder", "researcher", "analyst").
        task: Task description for the worker to execute.
        depends_on: List of step IDs that must complete before this step runs.
    """

    id: str = Field(..., description="Unique step identifier")
    worker: str = Field(..., description="Worker name from WORKER_REGISTRY")
    task: str = Field(..., description="Task description for the worker")
    depends_on: list[str] = Field(default_factory=list, description="Step IDs this step depends on")


class WorkflowPlan(BaseModel):
    """A multi-step execution plan generated by the Planner.

    Attributes:
        name: Name of the workflow (from template or LLM-generated).
        steps: Ordered list of workflow steps.
        reasoning: Explanation of why this plan was chosen.
    """

    name: str = Field(default="dynamic", description="Workflow name")
    steps: list[WorkflowStep] = Field(default_factory=list, description="Ordered workflow steps")
    reasoning: str = Field(default="", description="Planning reasoning")


class WorkflowState(BaseModel):
    """Main state for the Workflow graph.

    Attributes:
        messages: Conversation messages (with LangGraph add_messages reducer).
        long_term_memory: Retrieved long-term memory context.
        plan: The current workflow execution plan.
        completed_results: Accumulated results from all worker tasks (reducer: operator.add).
        current_round: Current execution round (for dependency-based scheduling).
        final_output: Synthesized final output from all worker results.
    """

    messages: Annotated[list, add_messages] = Field(
        default_factory=list, description="Conversation messages"
    )
    long_term_memory: str = Field(default="", description="Long-term memory context")
    plan: Optional[WorkflowPlan] = Field(default=None, description="Current workflow plan")
    completed_results: Annotated[list, operator.add] = Field(
        default_factory=list, description="Accumulated worker results"
    )
    current_round: int = Field(default=0, description="Current execution round")
    final_output: str = Field(default="", description="Synthesized final output")


class WorkerTaskState(BaseModel):
    """Per-worker state passed via Send API for parallel execution.

    Each worker receives its own isolated state containing the step definition,
    original messages for context, and writes results back to the parent
    graph's completed_results via the operator.add reducer.

    Attributes:
        step: The workflow step to execute.
        messages: Original conversation messages for context.
        completed_results: Results from this worker (merged into parent state).
        context_from_deps: Concatenated results from dependency steps.
    """

    step: WorkflowStep = Field(..., description="The step to execute")
    messages: list = Field(default_factory=list, description="Original conversation messages")
    completed_results: Annotated[list, operator.add] = Field(
        default_factory=list, description="Worker output results"
    )
    context_from_deps: str = Field(default="", description="Context from dependency steps")


class WorkerResult(BaseModel):
    """Result from a single worker task execution.

    Attributes:
        step_id: The step ID that produced this result.
        worker: The worker name that executed.
        task: The original task description.
        output: The worker's output content.
    """

    step_id: str = Field(..., description="Step ID")
    worker: str = Field(..., description="Worker name")
    task: str = Field(..., description="Original task")
    output: str = Field(..., description="Worker output content")
